// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REA.Emergencia.Data;

#nullable disable

namespace REA.Emergencia.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217171828_AddEmailLogs")]
    partial class AddEmailLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REA.Emergencia.Domain.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.CodigoPostal", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("ConcelhoId")
                        .HasColumnType("int");

                    b.Property<string>("Freguesia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Numero");

                    b.HasIndex("ConcelhoId");

                    b.ToTable("CodigosPostais", null, t =>
                        {
                            t.HasCheckConstraint("CK_CodigosPostais_Numero_Range", "[Numero] >= 1000000 AND [Numero] <= 9999999");
                        });
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Concelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Concelho");

                    b.Property<int?>("ZinfId")
                        .HasColumnType("int")
                        .HasColumnName("ZINFId");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.HasIndex("ZinfId");

                    b.ToTable("Concelhos", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Distrito");

                    b.HasKey("Id");

                    b.ToTable("Distritos", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SentAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("EmailLogs", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ExternalRequestID")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoPedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("ZinfId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TipoPedidoId");

                    b.HasIndex("ZinfId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.PedidoBem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Adults18Plus")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("CanPickUpNearby")
                        .HasColumnType("bit");

                    b.Property<int>("ChildrenUnder12")
                        .HasColumnType("int");

                    b.Property<string>("Concelho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FoodSupportInstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Freguesia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NeededProductTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OtherNeededProductTypesDetails")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ReceivesFoodSupport")
                        .HasColumnType("bit");

                    b.Property<int>("Seniors65Plus")
                        .HasColumnType("int");

                    b.Property<string>("Suggestions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Youth13To17")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PedidosBens", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.TipoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Workflow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposPedido", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.UserZinf", b =>
                {
                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ZinfId")
                        .HasColumnType("int");

                    b.HasKey("UserPrincipalName", "ZinfId");

                    b.HasIndex("ZinfId");

                    b.ToTable("UserZinfs", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Zinf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Zinfs", (string)null);
                });

            modelBuilder.Entity("REA.Emergencia.Domain.CodigoPostal", b =>
                {
                    b.HasOne("REA.Emergencia.Domain.Concelho", "Concelho")
                        .WithMany("CodigosPostais")
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concelho");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Concelho", b =>
                {
                    b.HasOne("REA.Emergencia.Domain.Distrito", "Distrito")
                        .WithMany("Concelhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REA.Emergencia.Domain.Zinf", "Zinf")
                        .WithMany("Concelhos")
                        .HasForeignKey("ZinfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Distrito");

                    b.Navigation("Zinf");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Pedido", b =>
                {
                    b.HasOne("REA.Emergencia.Domain.TipoPedido", "TipoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("TipoPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REA.Emergencia.Domain.Zinf", "Zinf")
                        .WithMany()
                        .HasForeignKey("ZinfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoPedido");

                    b.Navigation("Zinf");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.UserZinf", b =>
                {
                    b.HasOne("REA.Emergencia.Domain.Zinf", "Zinf")
                        .WithMany("UserZinfs")
                        .HasForeignKey("ZinfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zinf");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Concelho", b =>
                {
                    b.Navigation("CodigosPostais");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Distrito", b =>
                {
                    b.Navigation("Concelhos");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.TipoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("REA.Emergencia.Domain.Zinf", b =>
                {
                    b.Navigation("Concelhos");

                    b.Navigation("UserZinfs");
                });
#pragma warning restore 612, 618
        }
    }
}
